version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/extension"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/cloud-sync"
    schedule:
      interval: "weekly"

  - package-ecosystem: "cargo"
    directory: "/src-tauri"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/scripts/asr"
    schedule:
      interval: "weekly"
